language: python

python:
    - "3.6"

branches:
    only:
    - master

before_install:
    - "pip3 install -U pip"
    - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

cache: pip
install:
    - pip install -r requirements.txt

script: python linkcheck.py

